spring:
  datasource:
    username: hippo
    password: 2021Hippo
    url: jdbc:mysql://47.106.193.0:3306/fresh1?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
