server:
   port: 8080

spring:
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/fresh1?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: hippo
      password: 2021Hippo

# JWT配置
jwt:
   # 密匙Key
   secret: 2021Hippo
   # HeaderKey
   tokenHeader: Authorization
   # Token前缀
   tokenPrefix: Bearer
   # 过期时间，单位秒, 86400代表一天
   expiration: 86400
   # 配置白名单（不需要认证）注意， 逗号之间不能有空格
   antMatchers: /api/user/login,/api/user/register/**,/api/product/**
#   antMatchers: /api/user/register
   #springdata JPA配置
   jpa:
      database: MySQL
      hibernate:
         ddl-auto: update
      show-sql: true

